apiVersion: v1
kind: ServiceAccount
metadata:
  name: response-engine
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: response-engine-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: response-engine
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: response-engine
  labels:
    app: response-engine
spec:
  selector:
    matchLabels:
      app: response-engine
  template:
    metadata:
      labels:
        app: response-engine
    spec:
      serviceAccountName: response-engine
      containers:
      - image: ebriand/response-engine
        name: response-engine
        ports:
        - protocol: TCP
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: response-engine
spec:
  selector:
    app: response-engine
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
