apiVersion: apps/v1
kind: Deployment
metadata:
  name: response-engine
  labels:
    app: response-engine
spec:
  selector:
    matchLabels:
      app: response-engine
  template:
    metadata:
      labels:
        app: response-engine
    spec:
      containers:
      - image: response-engine:v1
        name: response-engine
        ports:
        - protocol: TCP
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: response-engine
spec:
  selector:
    app: response-engine
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
