apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln
  labels:
    app: vuln
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuln
  template:
    metadata:
      labels:
        app: vuln
    spec:
      containers:
        - name: vuln
          image: pyaillet/php-vulntest:local 
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              hostPort: 8080
      terminationGracePeriodSeconds: 3
