apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln
  labels:
    app: vuln
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuln
  template:
    metadata:
      labels:
        app: vuln
    spec:
      containers:
        - name: nginx
          image: nginx:1
          volumeMounts:
            - name: php
              mountPath: "/usr/share/nginx/html"
            - name: conf
              mountPath: "/etc/nginx/conf.d/"
          ports:
            - containerPort: 80
              hostPort: 8080
        - name: php
          image: php:7.2.10-fpm
          volumeMounts:
            - name: php
              mountPath: "/var/www/html"
      volumes:
        - name: php
          configMap:
            name: php
        - name: conf
          configMap:
            name: conf
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: vuln
#  labels:
#    app: vuln
#spec:
#  type: NodePort
#  selector:
#    app: vuln
#  ports:
#    - port: 80
#      nodePort: 30080
#      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: conf
data:
  default.conf: |
    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /usr/share/nginx/html;

        index index.html index.php;

        server_name _;

        location / {
            try_files $uri $uri/ =404;
        }

        location ~ [^/]\.php(/|$) {
            fastcgi_split_path_info ^(.+?\.php)(/.*)$;
            include fastcgi_params;

            fastcgi_param PATH_INFO       $fastcgi_path_info;
            fastcgi_index index.php;
            fastcgi_param  REDIRECT_STATUS    200;
            fastcgi_param  SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
            fastcgi_param  DOCUMENT_ROOT /var/www/html;
            fastcgi_pass localhost:9000;
        }

    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php
data:
  index.php: |
    <?php
    echo "hello world";
